
services:
    database:
        image: mysql:9.1.0
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: password
        ports:
            - "3306:3306"
        volumes:
            - ./docker/database:/var/lib/mysql:rw

    php-fpm:
        build:
            context: ./api
            target: php-fpm
        entrypoint: /mnt/php-fpm/entrypoint.sh
        env_file:
            -   ./docker/.env
        depends_on:
            - database
        restart: unless-stopped
        ports:
            - 9000
        volumes:
            - ./docker/php-fpm:/mnt/php-fpm

    nginx:
        image: nginx:1.27
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro