
services:
    database:
        image: mysql:9.1.0
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: password
        ports:
            - "3306:3306"
        volumes:
            - ./docker/database:/var/lib/mysql:rw
        labels:
            com.symfony.server.service-ignore: true

    php-fpm:
        build:
            context: ./api
            target: php-fpm
        entrypoint: /mnt/php-fpm/entrypoint.sh
        env_file:
            -   ./docker/.env
        depends_on:
            - database
        restart: unless-stopped
        ports:
            - "9000"
        volumes:
            - ./docker/php-fpm:/mnt/php-fpm
            - ./docker/php-fpm/usr/local/etc/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
            - ./api:/app

    nginx:
        image: nginx:1.27-alpine
        restart: unless-stopped
        # to refresh IP address of php-fpm
        healthcheck:
            test: ["CMD", "sh", "-c", "'[ ",  "$(curl", "-o", "/dev/null", "-I", "-L", "-s", "-w", "%{http_code}", "http://localhost:8000/docs", "-eq", "200", "]'"]
        ports:
            - "8000:80"
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./api/public:/app/api:ro
            - ./spa/app:/app/spa:ro

    spa:
        image: node:22-alpine
        command: npm install
        working_dir: /app
        volumes:
            - ./spa:/app:rw