services:
    database:
        image: mysql:9.1.0
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: main
        ports:
            - 3306:3306
    api:
        build:
            context: ./api
            target: api-php-fpm
        depends_on:
            - database
        restart: unless-stopped
        ports:
            - 8080:8080
        volumes:
            - ./api:/mnt/app