api_platform:
    title: Car rental managment system
    description: stworzone na potrzeby udziału w rekrutacji do firmy NEXAI
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        formats:
            json: ['application/json']
        pagination_enabled: false
        pagination_via_cursor_enabled: false
    error_formats:
        jsonproblem: ['application/problem+json']
    swagger:
        versions: [3]
    openapi:
        contact:
            name: Łukasz Osóbka
            email: lukasz.osobka@gmail.com
    enable_re_doc: false
    enable_swagger: true
    show_webby: false
    formats:
        json: ['application/json']