when@dev:
    web_profiler:
        toolbar: true
        intercept_redirects: false

    framework:
        profiler:
            only_exceptions: false
            collect_serializer_data: true
            dsn: 'file:/app/var/cache/test/profiler'

when@test:
    web_profiler:
        toolbar: false
        intercept_redirects: false

    framework:
        profiler: { enabled: true, collect: true }
