zenstruck_foundry:
    instantiator:
        use_constructor: true
    orm:
        auto_persist: true
        reset:
            connections: [ default ]
            entity_managers: [ default ]
            mode: schema

when@dev: &dev
    # See full configuration: https://symfony.com/bundles/ZenstruckFoundryBundle/current/index.html#full-default-bundle-configuration
    zenstruck_foundry:
        faker:
            locale: pl_PL
#when@dev: # see Bundle Configuration section about sharing this in the test environment
#    zenstruck_foundry:
        make_factory:
            default_namespace: 'App\\Factory'
when@test: *dev