api_platform:
    resource: .
    type: api_platform
    prefix: /
    
api_entrypoint:
    path: /{index}.{_format}
#    methods:
#        GET
#        HEAD
#    format: json
#    defaults:
#        _format: json
#    requirements:
#        _formatOther API docs:

#    <route id="api_entrypoint" path="/{index}.{_format}" methods="GET|HEAD">
#    <default key="_controller">api_platform.action.entrypoint</default>
#    <default key="_format" />
#    <default key="_api_respond">true</default>
#    <default key="index">index</default>
#
#    <requirement key="index">index</requirement>
#    </route>